### ISSUE TITLE
Emailing fails

### ISSUE THREAD

**Issue by leogeier** [snailsnap/mosaic#51]
On macOs 10.13.4, trying to send an email (by pressing 'M') fails with
`QAbstractSocket::waitForBytesWritten() is not allowed in UnconnectedState
QAbstractSocket::waitForBytesWritten() is not allowed in UnconnectedState
QAbstractSocket::waitForBytesWritten() is not allowed in UnconnectedState`

Attempting this a second time crashes the application.

**Comment by lukaswagner** [comment]
This seems to be broken on my PC too, while it's working fine on my laptop. Logs on start:
```
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_client_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_1_server_method
qt.network.ssl: QSslSocket: cannot resolve TLSv1_2_server_method
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_new
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_free
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_set_ssl_ctx
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_set_flags
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_CTX_finish
qt.network.ssl: QSslSocket: cannot resolve SSL_CONF_cmd
qt.network.ssl: QSslSocket: cannot resolve SSL_select_next_proto
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_next_proto_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_next_proto_negotiated
qt.network.ssl: QSslSocket: cannot resolve SSL_set_alpn_protos
qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
qt.network.ssl: QSslSocket: cannot resolve SSL_get0_alpn_selected
```
Log on mail command:
```
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get0_next_proto_negotiated
```
It seems that Qt doesn't properly connect to OpenSSL. We should take a look at this later, but for now we should work on other issues as long as it works at least one device.

**Comment by lukaswagner** [comment]
Turns out it doesn't actually fail on my PC, the mail got sent despite all the error messages.
