### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [snailsnap/mosaic#97]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by lukaswagner** [comment]
Hey, it's really nice that you want to help. But we actually already have an icon, we're using the [organization's avatar](https://avatars0.githubusercontent.com/u/39797762?s=200&v=4) to represent this project. Also, we're satisfied with this current icon. But thanks anyway for the offer :)
